modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "OL-SRR-2025"

[[mods]]
modId = "wyrms"
version = "${version}"
displayName = "Wyrms of Nyrus"
authors = "Modrome"
description = '''
Adds the invasive Nyral Wyrms to your Minecraft Worlds
'''
#logoFile = ""

[[dependencies.wyrms]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wyrms]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wyrms]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
